### ISSUE TITLE
Error found on _check_if_valid_collateral_for_market

### ISSUE THREAD

**Issue by diegodargos1** [snipermonke01/gmx_python_sdk#46]
I was trying to use IncreaseOrder and got stuck at the OrderArgumentParser
The error was:
if collateral_address == market['long_token_address']

I took a quick look and found the solution
            
<img width="735" alt="image" src="https://github.com/user-attachments/assets/e7b20b70-4b96-48ca-893f-96a38d5ee7a8">
           
Line 290 was missing the market_key           
           
I'm still not able to use the IncreaseOrder for other errors, but I'll let you know if I get it fixed.

**Comment by ShubhamPalriwala** [comment]
Hey @diegodargos1 I'm facing the same error as well:
```
Traceback (most recent call last):
  File "/home/shubham/Desktop/exponential/compiler/core/deploy/template/test.py", line 143, in <module>
    open_position(config=setup_gmx())
  File "/home/shubham/Desktop/exponential/compiler/core/deploy/template/test.py", line 120, in open_position
    ).process_parameters_dictionary(
  File "/home/shubham/Desktop/rsi-algo/rsi-algo/lib/python3.10/site-packages/gmx_python_sdk/scripts/v2/order/order_argument_parser.py", line 77, in process_parameters_dictionary
    self.missing_base_key_methods[missing_key]()
  File "/home/shubham/Desktop/rsi-algo/rsi-algo/lib/python3.10/site-packages/gmx_python_sdk/scripts/v2/order/order_argument_parser.py", line 220, in _handle_missing_collateral_address
    if self._check_if_valid_collateral_for_market(collateral_address) and not self.is_swap:
  File "/home/shubham/Desktop/rsi-algo/rsi-algo/lib/python3.10/site-packages/gmx_python_sdk/scripts/v2/order/order_argument_parser.py", line 293, in _check_if_valid_collateral_for_market
    if collateral_address == market['long_token_address'] or \
KeyError: 'long_token_address'
```

I found that I see the same error on any OrderArgumentParser config:
```py
    parameters = {
        "chain": 'arbitrum',

        # the market you want to trade on
        # "index_token_symbol": "BTC",
        "index_token_symbol": "SOL",

        # token to use as collateral. Start token swaps into collateral token
        # if different
        # "collateral_token_symbol": "BTC",
        "collateral_token_symbol": "SOL",

        # the token to start with - WETH not supported yet
        # "start_token_symbol": "USDC",
        "start_token_symbol": "USDC",

        # True for long, False for short
        "is_long": True,

        # Position size in in USD
        "size_delta_usd": 5,

        # if leverage is passed, will calculate number of tokens in
        # start_token_symbol amount
        "leverage": 2,

        # as a decimal ie 0.003 == 0.3%
        "slippage_percent": 0.003
    }
``` 
except for the (BTC, BTC, USDC) pair as commented above. Is this an SDK bug? How do I go about this? cc: @snipermonke01

**Comment by snipermonke01** [comment]
This has been fixed with this commit and will be included in the next release of the pip package. Currently available on the staging branch.

https://github.com/snipermonke01/gmx_python_sdk/commit/85ca4961187a0a72ab6015808f5845760149ac9c
